"""Quantumult X syntax stays at the output boundary."""

from string import Template

from src.models import Rule, RuleSet, ValidationError

TYPES = {
    "DOMAIN": "host",
    "DOMAIN-SUFFIX": "host-suffix",
    "IP-CIDR": "ip-cidr",
    "IP-CIDR6": "ip6-cidr",
}
HEADER = "# Generated by LoneRules. DO NOT EDIT; run python -m src.build.\n"


def render_rule(rule: Rule, policy: str) -> str:
    try:
        target_type = TYPES[rule.type]
    except KeyError as error:
        raise ValidationError(f"Quantumult X does not support {rule.type!r}") from error
    return f"{target_type},{rule.value},{policy}"


def render(ruleset: RuleSet) -> str:
    return HEADER + "\n".join(render_rule(rule, ruleset.name) for rule in ruleset.rules) + "\n"


def render_profile(rulesets: tuple[RuleSet, ...], template: str) -> str:
    policies = ["static = Proxy, direct, proxy"]
    for ruleset in rulesets:
        candidates = "direct, Proxy" if ruleset.name in {"Apple", "China"} else "Proxy, direct"
        policies.append(f"static = {ruleset.name}, {candidates}")
    # Keep domain matching ahead of IP matching, even across categories.
    lines = []
    for domain_phase in (True, False):
        for ruleset in rulesets:
            for rule in ruleset.rules:
                if rule.type.startswith("DOMAIN") == domain_phase:
                    lines.append(render_rule(rule, ruleset.name))
    try:
        return Template(template).substitute(
            generated=HEADER.rstrip(), policies="\n".join(policies), rules="\n".join(lines)
        )
    except (KeyError, ValueError) as error:
        raise ValidationError(f"invalid Quantumult X template: {error}") from error
